[auth]
enabled = true

[api]
enabled = true

[analytics]
enabled = false

[storage]
enabled = true

[edge_runtime]
enabled = true
policy = "per_worker"

[functions.delete-user]
verify_jwt = false

[functions.auth-callback]
verify_jwt = false

[functions.get-admin-stats]
verify_jwt = false

[functions.sms-webhook]
verify_jwt = false
